services:
  slmcp:
    image: slmcp:0.1
    container_name: slmcp
    ports:
      - "5678:5678"
    environment:
      - SAFELINE_SECRET=your_secret_key
      - SAFELINE_ADDRESS=https://your_safeline_ip:9443
      - SAFELINE_API_TOKEN=your_safeline_api_token
      - LISTEN_PORT=5678
      - LISTEN_ADDRESS=0.0.0.0
