name: Build and Push SLMCP Docker Image

on:
  push:
    branches:
      - master
    # paths:
    #   - "slmcp/**"
    tags:
      - "v*"
  pull_request:
    branches:
      - master
    paths:
      - "slmcp/**"

jobs:
  build-and-push:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./slmcp
          push: true
          tags: |
            chaitin/safeline-mcp:latest
            chaitin/safeline-mcp:${{ github.ref_name }}
          cache-from: type=registry,ref=chaitin/safeline-mcp:buildcache
          cache-to: type=registry,ref=chaitin/safeline-mcp:buildcache,mode=max
