name: Build and Push SLMCP Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "slmcp/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./slmcp
          push: true
          tags: |
            chaitin/safeline-mcp:latest
            chaitin/safeline-mcp:${{ github.ref_name }}
          cache-from: type=registry,ref=chaitin/safeline-mcp:buildcache
          cache-to: type=registry,ref=chaitin/safeline-mcp:buildcache,mode=max
